dist: trusty

sudo: required

language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - cmake
    - lcov

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Coverage ..
  - make
  - make nuflood_coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
