dist: xenial

sudo: required

language: cpp

branches:
  only:
  - master
  - development

compiler:
  - gcc

deploy:
   skip_cleanup: true

addons:
  apt:
    packages:
      - cmake
      - lcov
      - libgdal-dev
  artifacts:
    s3_region: ${AWS_REGION}
    paths: ${HOME}/build/lanl/nuflood/build/doc/html
    debug: true

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Coverage ..
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
