dist: trusty

sudo: required

language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - cmake
    - lcov

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Coverage ..
  - make
  - make nuflood_coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
